// src/pages/CropDetail.jsx
import React from "react";
import { useParams } from "react-router-dom";
import "../assets/cropdetail.css";

// Example crop details data
const cropDetailsData = {
  Mango: {
    name: "Mango",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Apple: {
    name: "Apple",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Banana: {
    name: "Banana",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Grapes: {
    name: "Grapes",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Mangoes: {
    name: "Mango",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Papaya: {
    name: "Papaya",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Pomegranate: {
    name: "Pomegranate",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Potato: {
    name: "Potato",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Tomato: {
    name: "Tomato",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Cabbage: {
    name: "Cabbage",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Cauliflower: {
    name: "Cauliflower",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Ladyfinger: {
    name: "Ladyfinger",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Onion: {
    name: "Onion",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  BottleGourd: {
    name: "BottleGourd",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Wheat: {
    name: "Wheat",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Rice: {
    name: "Rice",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Maize: {
    name: "Maize",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Bajra: {
    name: "Bajra",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Chana: {
    name: "Chana",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Soyabean: {
    name: "Soyabean",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Chawali: {
    name: "Chawali",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Masoor: {
    name: "Masoor",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Moong: {
    name: "Moong",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Mustard: {
    name: "Mustard",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Sesame: {
    name: "Sesame",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Tur: {
    name: "Tur",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Cotton: {
    name: "Cotton",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Groundnuts: {
    name: "Groundnuts",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Sugarcane: {
    name: "Sugarcane",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },
  Sunflower: {
    name: "Sunflower",
    prices: [
      { state: "Maharashtra", city: "Dhule", price: 2200 },
      { state: "Maharashtra", city: "Pune", price: 2100 },
      { state: "Maharashtra", city: "Nagpur", price: 2150 },
      { state: "Maharashtra", city: "Solapur", price: 2180 },
      { state: "Maharashtra", city: "Mumbai", price: 2250 },
      { state: "Madhya Pradesh", city: "Indore", price: 2150 },
      { state: "Madhya Pradesh", city: "Bhopal", price: 2180 },
      { state: "Madhya Pradesh", city: "Gwalior", price: 2200 },
      { state: "Madhya Pradesh", city: "Jabalpur", price: 2220 },
      { state: "Madhya Pradesh", city: "Ujjain", price: 2190 },
      { state: "Punjab", city: "Amritsar", price: 2300 },
      { state: "Punjab", city: "Ludhiana", price: 2280 },
      { state: "Punjab", city: "Jalandhar", price: 2270 },
      { state: "Punjab", city: "Patiala", price: 2290 },
      { state: "Punjab", city: "Bathinda", price: 2260 },
      { state: "Haryana", city: "Karnal", price: 2250 },
      { state: "Haryana", city: "Panipat", price: 2230 },
      { state: "Haryana", city: "Faridabad", price: 2240 },
      { state: "Haryana", city: "Hisar", price: 2220 },
      { state: "Haryana", city: "Rohtak", price: 2210 },
      { state: "Rajasthan", city: "Jaipur", price: 2190 },
      { state: "Rajasthan", city: "Jodhpur", price: 2170 },
      { state: "Rajasthan", city: "Udaipur", price: 2160 },
      { state: "Rajasthan", city: "Bikaner", price: 2180 },
      { state: "Rajasthan", city: "Ajmer", price: 2150 },
    ],
  },  

};

const CropDetail = () => {
  const { cropName } = useParams(); // e.g., 'apple'
  const crop = cropDetailsData[cropName];

  if (!crop) return <p>Crop not found</p>;

  return (
    <div className="crop-detail-container">
      <h1>{crop.name} Market Prices (per quintal)</h1>
      <table>
        <thead>
          <tr>
            <th>State</th>
            <th>City</th>
            <th>Price (₹)</th>
          </tr>
        </thead>
        <tbody>
          {crop.prices.map((item, index) => (
            <tr key={index}>
              <td>{item.state}</td>
              <td>{item.city}</td>
              <td>{item.price}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default CropDetail;
